- index.js
> fix: UIS-181 block scoped declarations not

- .gitignore
- index.js
add possibility to have multiple core.error procedure executions in different try catch blocks in one and the same procedure
> feat: multiple core.error procedure calls

- README.MD
- errors.js
- index.js
- package.json
This also includes improvements of error messages.
BREAKING CHANGE: errors are now thrown using lowercase first letter
> feat: allow call modifiers [], [^], [?], [0], [+]

- index.js
Since we cannot insert any value within a timestamp (rowversion) column (only DEFAULT or NULL can be passed as INSERT INTO parameter). Therefore we cannot use such columns is a Table-Type parameters (mssql creates a row with same definition and fails). In order to continue to use RowVersion columns it is safe just to change timestamp (rowversion) columns type (for auto-generated Table Types (TT and TTU)) to BINARY(8), so one can use these columns within a stored procedures without any conversion.
> fix: Remove rowversion columns from table types

- CHANGELOG.md
- README.MD
- index.js
- sql.js
To enable this feature must declare parameter db.create.diagram=true
> TSQL commands for enable/disable diagrams in database

- package.json
- sql.js
> fix: proper name escape

- package.json
- sql.js
like (dbo.sp_upgraddiagrams, dbo.fn_diagramobjects etc)
> fix: UTP-1232 exclude all objects owned by dbo

- index.js
BREAKING CHANGE: requires ut-port upgrade
> fix: refactor as class

- index.js
catch noAudit log flag from request headers
> noAudit log flag

- index.js
get encrypted values decrypted in backend
> feat: get encrypted values decrypted in backend

- index.js
This allows to split seed data from the SQL code that merges this data to the DB.
Seed data can come from .js or .json file. When the ports encounters a file
`xxx$module.entity.action.js[on]` it will call the respective SP named 
`module.entity.action` with parameters coming from the file. 
Usually seed data will be configured in port/module property named 'seed' as in this 
example: 
```js
var path = require('path');
module.exports = function sqlStandard({config}) {
return config && {seed: [{path: path.join(__dirname, 'standard'), config}]};
};
```
The file can export static data or a function. If it is a function, it will be executed 
with a single argument, corresponding to the value config in the above example.
The result of the function will be passed as parameters to the stored …
> feat: allow seed data coming from .js or .json

- index.js
always delete ***.json columns from resultSet
> fix: always delete ***.json columns from resultSet

- saveAs/index.js
> feat: encrypt file when exporting

- index.js
- processFiles.js
pass cbc to processFiles function
> fix: pass cbc to processFiles function

- index.js
- package.json
This make changes in ut-port-sql, to add support for using msnodesqlv8 driver
> feat: add support for using msnodesqlv8 driver

- processFiles.js
- sql.js
possibility to pass @objectId to --ut-permission-check
> feat: add possibility to pass @objectId to --ut-permission-check

- processFiles.js
- sql.js
allow multiple --ut-permission-check comments to be resolved in one and the same stored procedure
> feat: multiple permission check

- index.js
this MR goes along with MRs in ut-core and ut-user
> fix: BDC-1866 - pass auth.checkSession to SPs

- index.js
- package.json
expect potentially undefined or empty string error message resulting from DB request execution
> chore: expect potentially undefined or empty string error message

- index.js
> fix: retry attempts

- README.MD
- index.js
- package.json
- processFiles.js
> fix: pass errors to seed functions

- index.js
> fix: portSQL.retryFailedSchemas to be logged as 'fatal' #UTCORE-121

- .vscode/settings.json
- CHANGELOG.md
- errors.json
- index.js
- package.json
> Retries exceeded fatal error

- .vscode/launch.json
- package.json
- test/exec.test.js
- test/jobs/deadlock.js
- test/jobs/fetch.js
- test/jobs/index.js
- test/jobs/params.js
- test/jobs/private.js
- test/jobs/query.js
split tests into different jobs
> test: split tests into different jobs

- index.js
- package.json
- test/errors.json
- test/jobs/error.js
- test/jobs/index.js
- test/schema/750-test.test.errorParams.sql
> fix: sql error params

- test/jobs/params.js
- test/oracle.test.js
- test/schema/750-test.test.params.sql
make sure default values work for SP parameters
> chore: improve tests
